#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
------------------------------------
  _______          _         _ _ _
 |__   __|        | |       | | (_)
    | | __ _ _   _| |_ _   _| | |_
    | |/ _` | | | | __| | | | | | |
    | | (_| | |_| | |_| |_| | | | |
    |_|\__,_|\__,_|\__|\__,_|_|_|_|

------------------------------------'
echo "GID/UID
User uid:    $(id -u abc)
User gid:    $(id -g abc)
------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
